version: '3.4'
services:
  db:
    image: 'postgres:10-alpine'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: werkstatt
      POSTGRES_PASSWORD: werkstatt
      POSTGRES_DB: werkstatt
